/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.luiz.interfaceGrafica;

public class App {

    public static void main(String[] args) {
        TelaDeLogin telaLogin = new TelaDeLogin();
        telaLogin.pack();
        telaLogin.setVisible(true);
    }
}
